import OpenAI from "openai";
import { getValorantRankHistory } from "./valorant_api_helper.js";
import { ResponseInputItem, ResponseOutputMessage, Tool } from "openai/resources/responses/responses.js";
import { OPENAI_API_KEY, OPENAI_MODEL, VALORANT_RANK_PLAYER } from "../model/environment.js";

const openai = new OpenAI({
    apiKey: OPENAI_API_KEY,
});

const TOOL_API_NAME = "get_valorant_rank_history";

const tools: Tool[] = [
    {
        type: "function",
        name: TOOL_API_NAME,
        description: `Get ${VALORANT_RANK_PLAYER}'s Valorant rank history.`,
        parameters: {
            type: "object",
            properties: {
                pageNumber: {
                    type: "number",
                    description: `The page number to fetch of ${VALORANT_RANK_PLAYER}'s Valorant rank history. The page number is the same as the amount of games. If the not asked for page number of amount of games, assume the maximum number of games of 10.`,
                    minimum: 1,
                    maximum: 10,
                },
            },
            required: ["pageNumber"],
        },
        strict: null,
    },
];

async function getAnswerChatGpt(question: string): Promise<string | null> {
    let input: ResponseInputItem[] = [
        { role: "user", content: question },
    ];

    let response = await openai.responses.create({
        model: OPENAI_MODEL,
        input: input,
        tools,
        instructions: `Have the response relate to Valorant's rank player ${VALORANT_RANK_PLAYER}. Utilize the tools to get ${VALORANT_RANK_PLAYER} Valorant gameplay history.'`,
        tool_choice: "auto",
    });

    for (const item of response.output) {
        if (item.type === "function_call" && item.name === TOOL_API_NAME) {
            const args = JSON.parse(item.arguments);
            const valorantRankHistory = await getValorantRankHistory(args.pageNumber);

            input.push({
                type: "function_call",
                call_id: item.call_id,
                name: item.name,
                arguments: item.arguments
            });

            input.push({
                type: "function_call_output",
                call_id: item.call_id,
                output: valorantRankHistory.text,
            });
        }
    }

    response = await openai.responses.create({
        model: OPENAI_MODEL,
        instructions: `Respond relate with the ${VALORANT_RANK_PLAYER}'s Valorant rank information generated by the tools. If the content is not related to ${VALORANT_RANK_PLAYER}'s Valorant rank gameplay, respond with 'I am sorry, but your message is not related to Valorant's player ${VALORANT_RANK_PLAYER}.'`,
        tools,
        input,
    });

    for (const output of response.output) {
        if (output.type == "message") {
            const messageOutput = output as ResponseOutputMessage;
            if (messageOutput.status == "completed") {
                for (const item of output.content) {
                    if (item.type == "output_text") {
                        return item.text;
                    }
                }
            }
        }
    }

    return null;
}

export { getAnswerChatGpt };